### ISSUE TITLE
identifiers of independent task must be unique within the whole test

### ISSUE THREAD

**Issue by shevandrin** [shevandrin/rqti#100]
uniqueness within the section is not enough for the correct navigation in LMS

**Comment by shevandrin** [comment]
@bondarenko-petr write a test

**Comment by bondarenko-petr** [comment]
I have tested all sections on the unique identifiers of the items, all is ok.

**Comment by shevandrin** [comment]
task <- new("Essay", identifier = "id")
s1 <- section(task)
s2 <- section(task)
t <- test(list(s1, s2))
getIdentifier(t@section[[1]]@assessment_item[[1]])
getIdentifier(t@section[[2]]@assessment_item[[1]])

here there are two identical identifiers (==id) of the tasks in both sections
@bondarenko-petr put this case in tests
