### ISSUE TITLE
add grade scale to response processing 

### ISSUE THREAD

**Issue by shevandrin** [shevandrin/rqti#110]
in response processing recalculate SCORE variable according to grade scale

see scale here: https://johannestitz.com/en/post/2022-02-03-noten-intervalle-konsistent-berechnen/

jt: maybe also check how NOTE is related to qti test results, can we create it from SCORE or is it independent of qti results

- [x] add grade_lable to AssessmentTest
- [x] implement language dependent mechanic for grade_label
- [x] add new common feedback with factual grading scale
- [x] make upper border less on 0,01

**Comment by shevandrin** [comment]
@johannes-titz should we some how turn on/off this grading system?
in my opinion we need to provide this option.
We can do it on  class level (add specific slot to AsseessmentTest) or add parameter to the method createQtiTest().
What do you think?

**Comment by johannes-titz** [comment]
Yes, good idea. Right now I prefer it as a slot for AssessmentTest. What do you think?

**Comment by shevandrin** [comment]
I my opinion specific slot is more convenient way to manage this feature

**Comment by shevandrin** [comment]
@johannes-titz What could be as a default value for new slot 'grade_label'?

**Comment by johannes-titz** [comment]
How about language dependent? Can we check via environement variables of the os? If  not, "Grade: " makes sense as default.
