### ISSUE TITLE
add parameters for calculator and pdf file attachments

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/rqti#115]
for Rmd

**Comment by shevandrin** [comment]
Do you mean params in yaml section of Rmd? but both (calc and files) make sense for test creation (not question)

or you mean function test()?

**Comment by johannes-titz** [comment]
That's true. The underlying problem seems to be that two approaches are conflicting. If someones just works on one exercise with an Rmd file, he might never need the test creation functions. This is actually kind of true for the students that are working on th some exercises right now. 

We can discuss it in more detail when we meet.

**Comment by shevandrin** [comment]
@johannes-titz  during creating test from Rmd if it is found, that some of the attached files do not exist anymore, what we should do? error or warning?

**Comment by johannes-titz** [comment]
I am voting for error.

**Comment by shevandrin** [comment]
@bondarenko-petr cover with a test the case when file doesnt exist - it has to give an error

**Comment by johannes-titz** [comment]
also add to docs
