### ISSUE TITLE
documentation of classes

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/rqti#148]
For the slots, the defaults should be mentioned in the docs. For instance, in AssessmentTestOpal some defaults are missing. Also it would be nice to have a usage section, where one can also see the defaults.

This is referring to the help in R, not the pkgdown-docs.

**Comment by shevandrin** [comment]
I would also suggest to return construction functions at least for objects like `singleChoice()`

**Comment by johannes-titz** [comment]
Do we have them already? For all classes? If so, I guess they could refer to the class description as well?

**Comment by shevandrin** [comment]
we deleted them long time ago. Unfortunately, there is no formal connection between slots descriptions and params descriptions (that is why we deleted constructor functions). I experimented wit function factory to use slots as params,  but it doesnt give so much.

**Comment by johannes-titz** [comment]
Okay, we can discuss this again.

**Comment by shevandrin** [comment]
I would prefer to stick the format for the slots (and params) description.
It could be like this:
`param_name` Type [, optional]; description; default is `default_value`.

Default can be put at the end with collocation 'default is', if there is a set of possible values, one of them must be marked 'by default'

**Comment by shevandrin** [comment]
@johannes-titz one more question: should be implemented section `usage` instead of 'examples`?

**Comment by johannes-titz** [comment]
From my experience with non-S4 both are usually shown. Usage just shows the function call with defaults, whereas examples are more complex.
