### ISSUE TITLE
Prepare first release

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/rqti#149]
- [x] rename package, see changer package; new name rqti
- [x] update docs; specifically: introduction with project (quick start), instead of rmardkown files; also
- [x]  @johannes-titz reread once again, maybe there are some changes
- [x] change name from RQTI to rqti @bondarenko-petr 
- [x] build without errors, warnings, notes
- [x] note: reduce overall file size; new strategy: 
- [x] replace vignettes with articles pkgdown
- [x] note: do not use more than 20 packages; either kableExtra and/or id (maybe just use "ID"+random number); maybe fs; prioritize packages @bondarenko-petr 
- [x] run the whole procedure from the docs quick start (project template) once again on different OSes from scratch, in a virtual machine @bondarenko-petr
- [x] check if Tests and exercises can be imported into OpenOlat
- [x] check if Tests and exercises can be uploaded to some other LMS that supports QTI 2.1 and is non-proprietary; maybe something that is up to date and supported @bondarenko-petr
- [x]  check possibilities to adapt MultipleChoiceTable for Olat - done
- [x] add info about `compatibility `with Olat and Canvas in articles
- [x] check project file template @johannes-titz

**Comment by shevandrin** [comment]
> * note: reduce overall file size

to reach this goal, we need to keep our vignette folder less that 1 Mb, not it is about 4 Mb. It means, that we should not use graphic files. I dont see any other solution

**Comment by johannes-titz** [comment]
How about reducing quality of vignette images drastically? Or, not having vignettes at all, only pkdown articles?

**Comment by shevandrin** [comment]
we can start with reducing quality, then if it brings nothing we decide

**Comment by shevandrin** [comment]
> * change name from RQTI to rqti

do you mean in the titles of templates? @johannes-titz

**Comment by johannes-titz** [comment]
Actually, anywhere it is still RQTI, but I guess mainly in the templates.

**Comment by shevandrin** [comment]
> * check modal feedback and tolerance in Canvas

I  found that Canvas gives xml, made by qti 1.2: `xmlns=http://www.imsglobal.org/xsd/ims_qtiasiv1p2`
So I do not any opportunity to make some improvements for feedback and other properties like tolerance

**Comment by johannes-titz** [comment]
> > * check modal feedback and tolerance in Canvas
> 
> I found that Canvas gives xml, made by qti 1.2: `xmlns=http://www.imsglobal.org/xsd/ims_qtiasiv1p2` So I do not any opportunity to make some improvements for feedback and other properties like tolerance

Okay, so do we have any other LMS that we can test that supports 2.1?

**Comment by shevandrin** [comment]
according to wiki  we can try these: 
https://sourceforge.net/projects/qstonline/
https://en.wikipedia.org/wiki/TAO_(e-Testing_platform)

**Comment by johannes-titz** [comment]
Okay. Since everything seems to work fine with olat, I think we can postpone these tests to the second release. I will read the project main.R and then we should be ready.

**Comment by johannes-titz** [comment]
Strangely, here it says that 1.2 and 2.1 are supported by Canvas: https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-import-quizzes-from-QTI-packages/ta-p/1046
