### ISSUE TITLE
uploading as questionnaire

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/rqti#153]
For website methoden.guru it would be useful to take screenshots of entire exercise (for long exercises). In the normal preview this is not possible because the exercise is hidden inside an iframe. It might be possible via the opal questionnaire publishing feature, but only if this is manageable via API.

**Comment by shevandrin** [comment]
it is possible to upload on opal this type of resource FileResource.SURVEY - Ressource vom Typ **Fragebogen**
i can add it to the upload2opal() function
Questionnaire is not a test, it has some specific in xml structure, i need example of it.

**Comment by johannes-titz** [comment]
We can look into it after the first release. I just need to put the ideas somewhere external.

**Comment by shevandrin** [comment]
i created dummy Questionnaire, and i cant find any difference in xml with test at first glance))

**Comment by shevandrin** [comment]
upload2opal() now has param as_survey=F, you can upload zips with tests as surveys, but when i added some comment there, i can not find it anywhere. Seems the same problem as with TEST type.
Another problem, that we are not able to change resource type via API. For this reason, in case when current type and target type are not equal, i push an error.

**Comment by johannes-titz** [comment]
Great, thank you!

Makes sense with the resource type.

**Comment by johannes-titz** [comment]
I just tested it. Seems to work just fine. You can close this if you want.
