### ISSUE TITLE
answers_scores in directed pair docs

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/rqti#158]
### answers_scores

If it is important to have different values of points for different pairs, it is necessary to list these points in the same order that the pairs are defined in the list: `answers_scores: 2, 2, 1`. In this case, the total number of points will be calculated as the sum of 'answers_scores', and the attribute 'points', if set, will be ignored.

I think this is error prone. Do we need this? A match table can handle this case, I believe.

**Comment by shevandrin** [comment]
you mean it is better to rely only on points slot to deliver individual scores for answers for each pair?

**Comment by johannes-titz** [comment]
I would suggest to leave it undocumented as it might cause more trouble than be useful.

**Comment by shevandrin** [comment]
i will leave it at class docs, but remove from the article

**Comment by johannes-titz** [comment]
I can do it, I am working through the docs at the moment.
