### ISSUE TITLE
ignore html comments in rmd file

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/rqti#159]
`rstudioapi::documentOpen("inst/rmarkdown/templates/singlechoice-complex/skeleton/skeleton.Rmd")`

does not knit due to html comments. Can we ignore all html comments during conversion?

It would also be nice to have more meaningful error message when this happens.

**Comment by shevandrin** [comment]
i knited it with render_qtijs, render_opal and knitr::knit errorless.


> does not knit due to html comments. Can we ignore all html comments during conversion?

what kind of knitting do you mean?

**Comment by johannes-titz** [comment]
It seems I still had the old version, where this was not working.
