### ISSUE TITLE
docs table: managing identifiers

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/rqti#161]
For now I commented out the third way of specifying ids as I believe it might lead to confusion. If there is a demand for that we can add it again. But I think the abbreviation should be sufficient for most cases.

But I am wondering, what happens with the abbreviation if numbers are used (e.g. as in the multiplication table)?

**Comment by shevandrin** [comment]
> But I am wondering, what happens with the abbreviation if numbers are used (e.g. as in the multiplication table)?

from complex table template it gives: "4*9_="  "3*9_="  "5*5_="  "2*3_="  "12*3_=" as rows identifiers

**Comment by johannes-titz** [comment]
Are numbers allowed as ids? I thought this creates problems.

**Comment by shevandrin** [comment]
yes, it does not pass the verification due to numbers at the beginning:
```
Error: Xml file is not valid. 
c("Element '{http://www.imsglobal.org/xsd/imsqti_v2p1}simpleAssociableChoice', attribute 'identifier': '4*9_=' is not a valid value of the atomic type '{http://www.imsglobal.org/xsd/imsqti_v2p1}Identifier.Type'.", "Element '{http://www.imsglobal.org/xsd/imsqti_v2p1}simpleAssociableChoice', attribute 'identifier': '3*9_=' is not a valid value of the atomic type '{http://www.imsglobal.org/xsd/imsqti_v2p1}Identifier.Type'.", "Element '{http://www.imsglobal.org/xsd/imsqti_v2p1}simpleAssociableChoice', attribute 'identifier': '5*5_=' is not a valid value of the atomic type '{http://www.imsglobal.org/xsd/imsqti_v2p1}Identifier.Type'.", 
"Element '{http://www.imsglobal.org/xsd/imsqti_v2p1}simpleAssociableChoice', attribute 'identifier': '2*3_=' is not a valid value of the atomic type '{http://www.imsglobal.org/xsd/imsqti_v2p1}Identifier.Type'.", "Element '{http://www.imsglobal.org/xsd/imsqti_v2p1}simpleAssociableChoice', attribute 'identifier': '12*3_=' is not a
```
should i add some prefix at the beginning like `r`?

**Comment by shevandrin** [comment]
moreover, all special characters are not allowed to be in identifiers. so I eliminate them as well.
now for complex table template: 
rows identifiers are `"row49"  "row39"  "row55"  "row23"  "row123"`
cols identifiers are ` "col27" "col36" "col25" "col6" `

**Comment by johannes-titz** [comment]
So if it is invalid you are adding row/col to the identifier, right?

**Comment by shevandrin** [comment]
if it strarts with ditigs, col/row is added as prefix.
All symbols (except digits, letters and underscore) are removed in any case.
