### ISSUE TITLE
extract_results types for level = "items"

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/rqti#163]
score_candidate, score_max should be numerics, not characters, is_response_correct is a logical (not sure if we did integer on purpose?)

**Comment by shevandrin** [comment]
> is_response_correct is a logical (not sure if we did integer on purpose?)

this was made on purpose, but I don't remember the reason))

**Comment by shevandrin** [comment]
see issue #35  the second task

**Comment by johannes-titz** [comment]
Ok, still score_candidate and score_max should be changed.

**Comment by shevandrin** [comment]
done, if it meets your requirements, you can close this issue
