### ISSUE TITLE
installing from cran, missing qti.js

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/rqti#172]
render_qtijs does not work, I checked the folders and there is no qti.js. when installing from github, it works.

**Comment by shevandrin** [comment]
For some reason on my working folder qti.js was omitted. We can add it in the next release (it should be done not earlier after initial submission).

**Comment by johannes-titz** [comment]
I think we should do it now/soon; simply making a patch release. Otherwise the functionality is too restricted. It will not make sense to advertise the package if is not working as intended.

**Comment by shevandrin** [comment]
There other errors https://cran.r-project.org/web/checks/check_results_rqti.html
Do you know how to run these failed checks?

**Comment by johannes-titz** [comment]
I guess for the old release it is not so critical. Seems to be a pandoc issue?

**Comment by johannes-titz** [comment]
ok, that's a system dependency, not sure how to handle this. maybe there is something in the book?

**Comment by shevandrin** [comment]
new release 0.1.1 is now accessible on cran
