### ISSUE TITLE
add metadata in AI and AT

### ISSUE THREAD

**Issue by shevandrin** [shevandrin/rqti#179]
items of metadata (according to LOM):

1.  description
2.  version 
3.  format
4. rights

items of metadata from Opal:

1.  author
2.  Modified date
3.  Created date

@bondarenko-petr add new classes QtiMetadata and QtiContributor on the OOP scheme
TODO:

- [x] add ability to use environment variables to get values for metadata
- [x] add mechanics to assign metadata in Rmd
- [x] add metadata for test() and test4opal()
- [x] add creation zip with task only
- [x] add page on site about metadata

**Comment by johannes-titz** [comment]
Version refers to exercise version.

What is format again?

**Comment by shevandrin** [comment]
![image](https://github.com/shevandrin/rqti/assets/43883261/c3ae4f20-320a-4eb5-88ba-03ac412f181c)

format is qti version)

**Comment by shevandrin** [comment]
if we keep 'format' here, i would suggest to eliminate slot ' qti_versionl from AssessementItem and AssessmentTest

**Comment by johannes-titz** [comment]
I agree, this sounds reasonable.

**Comment by shevandrin** [comment]
LOM
├── Annotation
├── Classfication
├── Educational
├── General
│   ├── Aggregation Level
│   ├── Coverage
│   ├── Description
│   ├── Identifier
│   │   ├── Entry
│   │   └── Identifier
│   ├── Keyword
│   ├── Language
│   ├── Structure
│   └── Title
├── LifeCycle
│   ├── Contribute
│   │   ├── Date
│   │   ├── Entry
│   │   └── Role
│   ├── Status
│   └── Version
├── MetaMetadata
│   ├── Contribute
│   ├── Identifier_md
│   ├── Language
│   └── MetadataSchema
├── Relation
├── Rights
│   ├── CopyrightAndOtherDRestrictions
│   ├── Cost
│   └── Description
└── Technical
    ├── Duration
    ├── Format
    ├── InstallationRemarks
    ├── Location
    ├── OthePlatformRequirements
    ├── Requirement
    └── Size

**Comment by shevandrin** [comment]
this is a part of the whole tree of LOM. I can not find the place for 'created_date' and 'modified_date'. The only data, that i can suggest is date in 'contribute'. According to docu it means 'the date of contribution'. So i am confused: should i add new 'dates' of  keep the LOM structure?

**Comment by johannes-titz** [comment]
So Opal is using custom attributes? I think date of contribution is sufficient. authors can bump the version instead. Overall, version is more important.

**Comment by shevandrin** [comment]
In XMLs from Opal i cant find any tags that relates to creation and modification dates

**Comment by johannes-titz** [comment]
This is interesting: Es wird festgelegt, dass der <contribute>-Eintrag mit der Rolle Creator das Datum der letzten Änderung enthält. Außerdem wird festgelegt, dass der <contribute>-Eintrag mit der Rolle Validator das Datum der Veröffentlichung enthält.

Basically, if you are a creator, date is treated as last modification. If you are a validator, it is the publication date.

**Comment by shevandrin** [comment]
ok., i keep the date of contribution only

**Comment by shevandrin** [comment]
@bondarenko-petr for AssessmentItem and AsssessementSection add methods getContributors() on OOP scheme

**Comment by shevandrin** [comment]
@bondarenko-petr delete slot 'format' from QtiMetadata class

**Comment by shevandrin** [comment]
@bondarenko-petr add method getContributors() for 'character'

**Comment by shevandrin** [comment]
@bondarenko-petr cover creation QtiMetadata and QtiContributor classes, qti_metadata(), qti_contributor(), method createMetadata() with tests

**Comment by shevandrin** [comment]
@bondarenko-petr cover with tests appropriate transfer of metadata details from Rmd file
