### ISSUE TITLE
metadata message

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/rqti#183]
If authors are repeated, the message for collecting contributors should be adjusted. Currently I get things such as: 

Authors are found in exercises and added as contributors: Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz, Johannes Titz.

**Comment by shevandrin** [comment]
i have filtered contributors by 'contributor' and 'role' and now it takes only unique values

**Comment by shevandrin** [comment]
contribution date = current date
