### ISSUE TITLE
use 'scientific' for calculator type everywhere

### ISSUE THREAD

**Issue by shevandrin** [shevandrin/rqti#184]

**Comment by shevandrin** [comment]
@johannes-titz should we assign default calculator=NULL instead of calculator="scientific"?

`test4opal <- function(content, identifier = "test_identifier",
                      title = "Test Title", time_limit = 90L, max_attempts = 1L,
                      files = NULL, calculator = "scientific",`

because now it looks into tasks in `content` and if calculator was assigned there, it takes this value. I think we should do this when the creator put nothing to calculator in test4opal(), otherwise it has to take the value that was explicit given. For this reason NULL is more appropriate here.
@johannes-titz what is your opinion?

**Comment by johannes-titz** [comment]
Yes, NULL makes more sense.
