### ISSUE TITLE
get_course_results improvements

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/rqti#194]
- [x] should have an optional dir parameter to download in a specific directory; even better: path; if directory use default name; if path use actual path name for zip file, e.g. /download/myname.zip
- [x] default name could be the shortName ("results_shortName") instead of the ids, can we add a parameter "rename", which is TRUE by default; it renames to shortName, if FALSE it leaves the id name; what do you think?

**Comment by shevandrin** [comment]
> * default name could be the shortName ("results_shortName") instead of the ids, can we add a parameter "rename", which is TRUE by default; it renames to shortName, if FALSE it leaves the id name; what do you think?

good idea!

**Comment by johannes-titz** [comment]
Works without problems for me. Closing.
