### ISSUE TITLE
difference between rmd2xml and knitting rmd file

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/rqti#208]
When knitting, display information on SCORE and MAXSCORE are stored in the xml file. I believe it would be better to calculate these values in qtijs directly. To be more specific, this part:

```
<div class="rqti-ai-result">Score:
<printedVariable identifier="SCORE" format="%d"/>(Max score:
<printedVariable identifier="MAXSCORE" format="%d"/>)</div>
```

is only there when knitting, not when running rmd2xml. The generated xmls differ. It is the responsibility of qtijs to render from the xml the score and max score.

**Comment by shevandrin** [comment]
qtijs engine works with printedVariable to display some values. I defined both. Othewise it gives nothing to print

**Comment by johannes-titz** [comment]
But is this part of the xml file?

**Comment by shevandrin** [comment]
yes, part of xml

**Comment by johannes-titz** [comment]
My problem is: when knitting the xml contains the score and max score; what happens when i upload this file to opal? it will have an extra score and max score. This is not always wanted. When i use rmd2xml this does not happen. Is it not possible to access these variables form js directly? For instance, the submit button is also not part of the xml.

**Comment by shevandrin** [comment]
it is possible, but it requires to change qtijs engine, now it works only with printed variables to show outcome

**Comment by johannes-titz** [comment]
How hard is it to access variables via js? How does it get the title? Also via printed variables?

Think of this scenario: I have an xml file that was not created via rqti; it has somewhere stored score and maxscore; qtijs should be able to display this information. This displaying should not depend on us defining it in the xml.

**Comment by shevandrin** [comment]
original qtijs does not display this. I do not think that it is hard, but still takes time

**Comment by johannes-titz** [comment]
Ok, I think it would be nice to have. But the article has higher priority right now. So we can come back to this later.
