### ISSUE TITLE
what is the default value of points for dropdown (1 or 0.5 for each selection?)

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/rqti#216]

**Comment by shevandrin** [comment]
each dropdown gives only one response, in case of true response the users will be granted 1 point.
How many selections dropodown has does not make sense, because only one selection as a response is possible.

**Comment by johannes-titz** [comment]
I mean "selection=dropdown" (when having multiple in one exercise). 1 makes sense if it is also used for sc.

**Comment by shevandrin** [comment]
like in a gap, each instance dropdown give 1 point
