### ISSUE TITLE
add warning when essay is used with conditional feedback

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/rqti#217]
Because of manual grading, conditional feedback does not make sense. user should be warned (maybe we do this already?)

**Comment by shevandrin** [comment]
![image](https://github.com/user-attachments/assets/cf8437c2-ffa1-48ea-9f07-0cecf7b6deb2)
now it returns an Error, when one of the feedbacks is conditional

**Comment by johannes-titz** [comment]
Good, works for me!
