### ISSUE TITLE
errors and warnings for RMD files

### ISSUE THREAD

**Issue by johannes-titz** [shevandrin/rqti#92]
- [x] error when no # question section is provided
- [x] show error when library(qti) is not called but helpers are used
- [x] meaningful error message when type is missing

**Comment by johannes-titz** [comment]
User forgot to specify type in the yaml.

**Comment by shevandrin** [comment]
@bondarenko-petr cover with tests

**Comment by shevandrin** [comment]
should we take into account this way to call 'qti' in Rmd:
`librarian::shelf(ggplot2, dplyr, qti)`
now it gives an error, because 'qti' looks only `library(qti)`

**Comment by johannes-titz** [comment]
I guess that would be good.
